//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisBuddy.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BisBuddy.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Advanced] .
        /// </summary>
        public static string AdvancedMateriaMeldTooltip {
            get {
                return ResourceManager.GetString("AdvancedMateriaMeldTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias for {0}.
        /// </summary>
        public static string AliasChatCommandHelpMessage {
            get {
                return ResourceManager.GetString("AliasChatCommandHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark all as not Collected.
        /// </summary>
        public static string AllCollectedTooltip {
            get {
                return ResourceManager.GetString("AllCollectedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock all as Collected.
        /// </summary>
        public static string AllUncollectedTooltip {
            get {
                return ResourceManager.GetString("AllUncollectedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as not Collected.
        /// </summary>
        public static string AutomaticallyCollectedTooltip {
            get {
                return ResourceManager.GetString("AutomaticallyCollectedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bright List Items.
        /// </summary>
        public static string BrightListItemHighlightingCheckbox {
            get {
                return ResourceManager.GetString("BrightListItemHighlightingCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locks list item highlight opacity to max to increase contrast. Disabling may fix issues with some custom UIs.
        /// </summary>
        public static string BrightListItemHighlightingHelp {
            get {
                return ResourceManager.GetString("BrightListItemHighlightingHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Locked] {0}.
        /// </summary>
        public static string CollectionStatusLockedTooltipPrefix {
            get {
                return ResourceManager.GetString("CollectionStatusLockedTooltipPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection status locked.
        /// </summary>
        public static string CollectionStatusLockTooltip {
            get {
                return ResourceManager.GetString("CollectionStatusLockTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect.
        /// </summary>
        public static string CollectVerb {
            get {
                return ResourceManager.GetString("CollectVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new gearset.
        /// </summary>
        public static string CommandDescriptionAddGearset {
            get {
                return ResourceManager.GetString("CommandDescriptionAddGearset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open plugin configuration.
        /// </summary>
        public static string CommandDescriptionOpenConfig {
            get {
                return ResourceManager.GetString("CommandDescriptionOpenConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open plugin debug if debugging is enabled.
        /// </summary>
        public static string CommandDescriptionOpenDebug {
            get {
                return ResourceManager.GetString("CommandDescriptionOpenDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugging.
        /// </summary>
        public static string ConfigDebugSectionHeader {
            get {
                return ResourceManager.GetString("ConfigDebugSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        public static string ConfigGeneralSectionHeader {
            get {
                return ResourceManager.GetString("ConfigGeneralSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Highlighting.
        /// </summary>
        public static string ConfigHighlightingSectionHeader {
            get {
                return ResourceManager.GetString("ConfigHighlightingSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Updates.
        /// </summary>
        public static string ConfigInventorySectionHeader {
            get {
                return ResourceManager.GetString("ConfigInventorySectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        public static string ConfigTabName {
            get {
                return ResourceManager.GetString("ConfigTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Styles.
        /// </summary>
        public static string ConfigUiThemeSectionHeader {
            get {
                return ResourceManager.GetString("ConfigUiThemeSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Config.
        /// </summary>
        public static string ConfigWindowTitle {
            get {
                return ResourceManager.GetString("ConfigWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy JSON.
        /// </summary>
        public static string ContextMenuCopyJson {
            get {
                return ResourceManager.GetString("ContextMenuCopyJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy {0} text.
        /// </summary>
        public static string ContextMenuCopyString {
            get {
                return ResourceManager.GetString("ContextMenuCopyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy {0} link.
        /// </summary>
        public static string ContextMenuCopyUrl {
            get {
                return ResourceManager.GetString("ContextMenuCopyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Gearset.
        /// </summary>
        public static string ContextMenuDeleteGearset {
            get {
                return ResourceManager.GetString("ContextMenuDeleteGearset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock all as Collected.
        /// </summary>
        public static string ContextMenuLockAllCollected {
            get {
                return ResourceManager.GetString("ContextMenuLockAllCollected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock all as Uncollected.
        /// </summary>
        public static string ContextMenuLockAllUncollected {
            get {
                return ResourceManager.GetString("ContextMenuLockAllUncollected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock as Collected.
        /// </summary>
        public static string ContextMenuLockCollected {
            get {
                return ResourceManager.GetString("ContextMenuLockCollected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock as Uncollected.
        /// </summary>
        public static string ContextMenuLockUncollected {
            get {
                return ResourceManager.GetString("ContextMenuLockUncollected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in Inventory.
        /// </summary>
        public static string ContextMenuSearchInventory {
            get {
                return ResourceManager.GetString("ContextMenuSearchInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock.
        /// </summary>
        public static string ContextMenuUnlock {
            get {
                return ResourceManager.GetString("ContextMenuUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock all.
        /// </summary>
        public static string ContextMenuUnlockAll {
            get {
                return ResourceManager.GetString("ContextMenuUnlockAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addon Highlights.
        /// </summary>
        public static string DebugAddonsTab {
            get {
                return ResourceManager.GetString("DebugAddonsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throw Error.
        /// </summary>
        public static string DebugFrameworkThreadBehaviorAssertName {
            get {
                return ResourceManager.GetString("DebugFrameworkThreadBehaviorAssertName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throw an exception. WARNING: Can break functionality if errors are encountered.
        /// </summary>
        public static string DebugFrameworkThreadBehaviorAssertTooltip {
            get {
                return ResourceManager.GetString("DebugFrameworkThreadBehaviorAssertTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do Nothing.
        /// </summary>
        public static string DebugFrameworkThreadBehaviorIgnoreName {
            get {
                return ResourceManager.GetString("DebugFrameworkThreadBehaviorIgnoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore the issue and continue. Please only use if warnings are flooding the console and the issue has been reported.
        /// </summary>
        public static string DebugFrameworkThreadBehaviorIgnoreTooltip {
            get {
                return ResourceManager.GetString("DebugFrameworkThreadBehaviorIgnoreTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Warning.
        /// </summary>
        public static string DebugFrameworkThreadBehaviorWarningName {
            get {
                return ResourceManager.GetString("DebugFrameworkThreadBehaviorWarningName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log a warning to the console. Default behavior.
        /// </summary>
        public static string DebugFrameworkThreadBehaviorWarningTooltip {
            get {
                return ResourceManager.GetString("DebugFrameworkThreadBehaviorWarningTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Requirements.
        /// </summary>
        public static string DebugItemRequirementsTab {
            get {
                return ResourceManager.GetString("DebugItemRequirementsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Prerequisites.
        /// </summary>
        public static string DebugPrerequisitesTab {
            get {
                return ResourceManager.GetString("DebugPrerequisitesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Solver Results.
        /// </summary>
        public static string DebugSolverResultsTab {
            get {
                return ResourceManager.GetString("DebugSolverResultsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string DebugTabName {
            get {
                return ResourceManager.GetString("DebugTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Gearset.
        /// </summary>
        public static string DefaultNewGearsetName {
            get {
                return ResourceManager.GetString("DefaultNewGearsetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, Delete.
        /// </summary>
        public static string DeleteGearsetConfirmButton {
            get {
                return ResourceManager.GetString("DeleteGearsetConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This cannot be undone!.
        /// </summary>
        public static string DeleteGearsetConfirmTooltip {
            get {
                return ResourceManager.GetString("DeleteGearsetConfirmTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift+Click to delete {0}.
        /// </summary>
        public static string DeleteGearsetDisabledTooltip {
            get {
                return ResourceManager.GetString("DeleteGearsetDisabledTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Gearset?.
        /// </summary>
        public static string DeleteGearsetPopupTitle {
            get {
                return ResourceManager.GetString("DeleteGearsetPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}.
        /// </summary>
        public static string DeleteGearsetTooltip {
            get {
                return ResourceManager.GetString("DeleteGearsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selected gearset.
        /// </summary>
        public static string DeleteGearsetTooltipGearsetNameDummy {
            get {
                return ResourceManager.GetString("DeleteGearsetTooltipGearsetNameDummy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this Gearset. Click to quick delete.
        /// </summary>
        public static string DeleteGearsetTooltipQuick {
            get {
                return ResourceManager.GetString("DeleteGearsetTooltipQuick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Gearset.
        /// </summary>
        public static string DisabledGearsetTooltip {
            get {
                return ResourceManager.GetString("DisabledGearsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string DisabledGearsetVerb {
            get {
                return ResourceManager.GetString("DisabledGearsetVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} disabled, configure in toggles.
        /// </summary>
        public static string DisabledPrerequisiteTooltip {
            get {
                return ResourceManager.GetString("DisabledPrerequisiteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Gearset.
        /// </summary>
        public static string EnabledGearsetTooltip {
            get {
                return ResourceManager.GetString("EnabledGearsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string EnabledGearsetVerb {
            get {
                return ResourceManager.GetString("EnabledGearsetVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. Right click to lock.
        /// </summary>
        public static string GearpieceCollectionStatusUnlockedSuffix {
            get {
                return ResourceManager.GetString("GearpieceCollectionStatusUnlockedSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///Right click + Lock gearpiece to change status.
        /// </summary>
        public static string GearpieceLockedDisabledTooltip {
            get {
                return ResourceManager.GetString("GearpieceLockedDisabledTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Materia/Prerequisites.
        /// </summary>
        public static string GearpieceNoSubItemsTooltip {
            get {
                return ResourceManager.GetString("GearpieceNoSubItemsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Default.
        /// </summary>
        public static string GearsetDefaultColorCheckbox {
            get {
                return ResourceManager.GetString("GearsetDefaultColorCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to use the default highlight color (as set in configuration),
        ///or to have a unique color to highlight items in.
        /// </summary>
        public static string GearsetDefaultColorTooltip {
            get {
                return ResourceManager.GetString("GearsetDefaultColorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gearpieces.
        /// </summary>
        public static string GearsetGearpiecesTabName {
            get {
                return ResourceManager.GetString("GearsetGearpiecesTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color needed items for this gearset are highlighted in.
        /// </summary>
        public static string GearsetHighlightColorButtonTooltip {
            get {
                return ResourceManager.GetString("GearsetHighlightColorButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Color.
        /// </summary>
        public static string GearsetHighlightColorLabel {
            get {
                return ResourceManager.GetString("GearsetHighlightColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON.
        /// </summary>
        public static string GearsetJsonButton {
            get {
                return ResourceManager.GetString("GearsetJsonButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy gearset JSON to clipboard.
        /// </summary>
        public static string GearsetJsonTooltip {
            get {
                return ResourceManager.GetString("GearsetJsonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight Color.
        /// </summary>
        public static string GearsetPropertiesColorRowLabel {
            get {
                return ResourceManager.GetString("GearsetPropertiesColorRowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Export.
        /// </summary>
        public static string GearsetPropertiesDataRowLabel {
            get {
                return ResourceManager.GetString("GearsetPropertiesDataRowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Date.
        /// </summary>
        public static string GearsetPropertiesImportDateRowLabel {
            get {
                return ResourceManager.GetString("GearsetPropertiesImportDateRowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Source.
        /// </summary>
        public static string GearsetPropertiesSourceTypeRowLabel {
            get {
                return ResourceManager.GetString("GearsetPropertiesSourceTypeRowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gearset Status.
        /// </summary>
        public static string GearsetPropertiesStatusRowLabel {
            get {
                return ResourceManager.GetString("GearsetPropertiesStatusRowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string GearsetPropertiesTabName {
            get {
                return ResourceManager.GetString("GearsetPropertiesTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string GearsetSortActive {
            get {
                return ResourceManager.GetString("GearsetSortActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string GearsetSortImportDate {
            get {
                return ResourceManager.GetString("GearsetSortImportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        public static string GearsetSortJob {
            get {
                return ResourceManager.GetString("GearsetSortJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string GearsetSortName {
            get {
                return ResourceManager.GetString("GearsetSortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string GearsetSortPriority {
            get {
                return ResourceManager.GetString("GearsetSortPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to view/add gearsets.
        /// </summary>
        public static string GearsetsTabLoggedOutText {
            get {
                return ResourceManager.GetString("GearsetsTabLoggedOutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teamcraft.
        /// </summary>
        public static string GearsetStringButton {
            get {
                return ResourceManager.GetString("GearsetStringButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy {0} text to clipboard.
        /// </summary>
        public static string GearsetStringTooltip {
            get {
                return ResourceManager.GetString("GearsetStringTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string GearsetUrlButton {
            get {
                return ResourceManager.GetString("GearsetUrlButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy {0} link to clipboard.
        /// </summary>
        public static string GearsetUrlTooltip {
            get {
                return ResourceManager.GetString("GearsetUrlTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight Appearance.
        /// </summary>
        public static string GeneralConfigurationHighlightAppearanceCategory {
            get {
                return ResourceManager.GetString("GeneralConfigurationHighlightAppearanceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        public static string GeneralConfigurationMiscellaneousCategory {
            get {
                return ResourceManager.GetString("GeneralConfigurationMiscellaneousCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Collected.
        /// </summary>
        public static string HighlightCollectedInInventoryCheckbox {
            get {
                return ResourceManager.GetString("HighlightCollectedInInventoryCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to highlight items in player inventories (inventory, retainer, saddlebag) that are marked as collected..
        /// </summary>
        public static string HighlightCollectedInInventoryHelp {
            get {
                return ResourceManager.GetString("HighlightCollectedInInventoryHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collected Only.
        /// </summary>
        public static string HighlightCollectedItemMateriaCheckbox {
            get {
                return ResourceManager.GetString("HighlightCollectedItemMateriaCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Highlight Color.
        /// </summary>
        public static string HighlightColorButtonLabel {
            get {
                return ResourceManager.GetString("HighlightColorButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color needed items are highlighted in by default or with color conflicts.
        /// </summary>
        public static string HighlightColorButtonTooltip {
            get {
                return ResourceManager.GetString("HighlightColorButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What color to highlight needed items in by default, or if an item is needed by gearsets different colors
        ///
        ///Use alpha channel to adjust highlight intensity on items/icons
        ///List menu highlights are not affected.
        /// </summary>
        public static string HighlightColorHelp {
            get {
                return ResourceManager.GetString("HighlightColorHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventories.
        /// </summary>
        public static string HighlightInventoriesCheckbox {
            get {
                return ResourceManager.GetString("HighlightInventoriesCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlights items needed for gearsets in inventories (inventory, retainer, saddlebag).
        /// </summary>
        public static string HighlightInventoriesHelp {
            get {
                return ResourceManager.GetString("HighlightInventoriesHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Tooltips.
        /// </summary>
        public static string HighlightItemTooltipsCheckbox {
            get {
                return ResourceManager.GetString("HighlightItemTooltipsCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists what gearsets need the item being hovered over in the item tooltip.
        /// </summary>
        public static string HighlightItemTooltipsHelp {
            get {
                return ResourceManager.GetString("HighlightItemTooltipsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketboard.
        /// </summary>
        public static string HighlightMarketboardCheckbox {
            get {
                return ResourceManager.GetString("HighlightMarketboardCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlights items needed for gearsets on the marketboard.
        /// </summary>
        public static string HighlightMarketboardHelp {
            get {
                return ResourceManager.GetString("HighlightMarketboardHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materia Melding.
        /// </summary>
        public static string HighlightMateriaMeldingCheckbox {
            get {
                return ResourceManager.GetString("HighlightMateriaMeldingCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlights gearpieces needing melds and the materia needed for those gearpieces in melding windows.
        /// </summary>
        public static string HighlightMateriaMeldingHelp {
            get {
                return ResourceManager.GetString("HighlightMateriaMeldingHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need/Greed Windows.
        /// </summary>
        public static string HighlightNeedGreedCheckbox {
            get {
                return ResourceManager.GetString("HighlightNeedGreedCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlights items needed for gearsets in Need/Greed loot windows.
        /// </summary>
        public static string HighlightNeedGreedHelp {
            get {
                return ResourceManager.GetString("HighlightNeedGreedHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Materia Only.
        /// </summary>
        public static string HighlightNextMateriaCheckbox {
            get {
                return ResourceManager.GetString("HighlightNextMateriaCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to only highlight the next materia, or to highlight all available materia to meld. Useful for advanced melding
        ///Note: Ensure no erroneous materia is already melded for most accurate highlighting
        ///
        ///When ON: Only the next materia a gearpiece needs to meld is highlighted
        ///When OFF: All materia a gearpiece needs is highlighted in the melding window
        ///
        ///Example
        ///Gearpiece needs the following melds: [+36 CRT, +36 DET]
        ///
        ///When ON: +36 CRT is highlighted
        ///When OFF: +36 CRT and +36 DET are highlighted.
        /// </summary>
        public static string HighlightNextMateriaHelp {
            get {
                return ResourceManager.GetString("HighlightNextMateriaHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meld Prerequisites.
        /// </summary>
        public static string HighlightPrerequisiteMateriaCheckbox {
            get {
                return ResourceManager.GetString("HighlightPrerequisiteMateriaCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether prerequisites should be considered meld targets for the materia listed for gearpieces they are a prerequisite for
        ///
        ///When ON: Prerequisites will be highlighted when melding materia, requiring the materia the final gearpiece needs.
        ///The gearpiece in the menu will reflect the melds of the prerequisite while it is not yet obtained.
        ///When OFF: Only the main gearpiece will be highlighted when melding materia.
        ///
        ///Example
        ///Gearpiece (unobtained): Augmented Historia Ring of Casting [+54 DET, +54 CRT]
        ///Prere [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HighlightPrerequisiteMateriaHelp {
            get {
                return ResourceManager.GetString("HighlightPrerequisiteMateriaHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shops/Exchanges.
        /// </summary>
        public static string HighlightShopExchangesCheckbox {
            get {
                return ResourceManager.GetString("HighlightShopExchangesCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlights items needed for gearsets in NPC shops/item exchanges.
        /// </summary>
        public static string HighlightShopExchangesHelp {
            get {
                return ResourceManager.GetString("HighlightShopExchangesHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncollected Item Materia.
        /// </summary>
        public static string HighlightUncollectedItemMateriaCheckbox {
            get {
                return ResourceManager.GetString("HighlightUncollectedItemMateriaCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether materia needed for gearpieces that are not yet collected should be highlighted.
        ///
        ///When ON: Materia needed for gearpieces will be highlighted regardless of collected status
        ///When OFF: If a gearpiece isn&apos;t collected, its materia will not be highlighted anywhere.
        /// </summary>
        public static string HighlightUncollectedItemMateriaHelp {
            get {
                return ResourceManager.GetString("HighlightUncollectedItemMateriaHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etro.
        /// </summary>
        public static string ImportEtroName {
            get {
                return ResourceManager.GetString("ImportEtroName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gearset sheet link from Etro.gg
        ///ex: https://etro.gg/gearset/4b5f4ed3-4832-4fd5-b134-3429ea8caf37.
        /// </summary>
        public static string ImportEtroTooltip {
            get {
                return ResourceManager.GetString("ImportEtroTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Fail:.
        /// </summary>
        public static string ImportFailBase {
            get {
                return ResourceManager.GetString("ImportFailBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Internal error.
        /// </summary>
        public static string ImportFailInternalError {
            get {
                return ResourceManager.GetString("ImportFailInternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Invalid input for {1}.
        /// </summary>
        public static string ImportFailInvalidInput {
            get {
                return ResourceManager.GetString("ImportFailInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Invalid response received.
        /// </summary>
        public static string ImportFailInvalidResponse {
            get {
                return ResourceManager.GetString("ImportFailInvalidResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} No gearsets found/imported.
        /// </summary>
        public static string ImportFailNoGearsets {
            get {
                return ResourceManager.GetString("ImportFailNoGearsets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} No response from server.
        /// </summary>
        public static string ImportFailNoResponse {
            get {
                return ResourceManager.GetString("ImportFailNoResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Must be logged in to import gearsets.
        /// </summary>
        public static string ImportFailNotLoggedIn {
            get {
                return ResourceManager.GetString("ImportFailNotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Import would exceed gearset limit.
        /// </summary>
        public static string ImportFailTooManyGearsets {
            get {
                return ResourceManager.GetString("ImportFailTooManyGearsets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from {0}.
        /// </summary>
        public static string ImportGearsetButton {
            get {
                return ResourceManager.GetString("ImportGearsetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string ImportGearsetLoading {
            get {
                return ResourceManager.GetString("ImportGearsetLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to import gearsets.
        /// </summary>
        public static string ImportGearsetLoggedOut {
            get {
                return ResourceManager.GetString("ImportGearsetLoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import a new gearset from {0}.
        /// </summary>
        public static string ImportGearsetTooltip {
            get {
                return ResourceManager.GetString("ImportGearsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL.
        /// </summary>
        public static string ImportInvalidUrl {
            get {
                return ResourceManager.GetString("ImportInvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON.
        /// </summary>
        public static string ImportJsonName {
            get {
                return ResourceManager.GetString("ImportJsonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gearset JSON exported from existing plugin gearset
        ///ex: {&quot;Id&quot;:&quot;50399235-5794-4ccb-906f-ddd9....
        /// </summary>
        public static string ImportJsonTooltip {
            get {
                return ResourceManager.GetString("ImportJsonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Gearsets Found.
        /// </summary>
        public static string ImportNoGearsets {
            get {
                return ResourceManager.GetString("ImportNoGearsets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Success: {2} gearset(s) imported.
        /// </summary>
        public static string ImportSuccess {
            get {
                return ResourceManager.GetString("ImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teamcraft.
        /// </summary>
        public static string ImportTeamcraftName {
            get {
                return ResourceManager.GetString("ImportTeamcraftName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plaintext gearset exported from Teamcraft
        ///ex:
        ///**Everseeker&apos;s Pickaxe HQ**
        ///        
        ///- Gatherer&apos;s Guile Materia X
        ///
        ///**Everseeker&apos;s Coat of Gath....
        /// </summary>
        public static string ImportTeamcraftTooltip {
            get {
                return ResourceManager.GetString("ImportTeamcraftTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Gearset.
        /// </summary>
        public static string ImportWindowTitle {
            get {
                return ResourceManager.GetString("ImportWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xivgear.
        /// </summary>
        public static string ImportXivgearName {
            get {
                return ResourceManager.GetString("ImportXivgearName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gearset sheet link exported from Xivgear.app
        ///ex: https://xivgear.app/?page=sl%%7C9ee61d69-7daa-41bd-9c28-8a0f0055f90f.
        /// </summary>
        public static string ImportXivgearTooltip {
            get {
                return ResourceManager.GetString("ImportXivgearTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string InventoryScanLoading {
            get {
                return ResourceManager.GetString("InventoryScanLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} gearpieces updated.
        /// </summary>
        public static string InventoryScanUpdated {
            get {
                return ResourceManager.GetString("InventoryScanUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string ItemExchangesTabName {
            get {
                return ResourceManager.GetString("ItemExchangesTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Planner.
        /// </summary>
        public static string ItemPlannerTabName {
            get {
                return ResourceManager.GetString("ItemPlannerTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Tracker.
        /// </summary>
        public static string ItemTrackerTabName {
            get {
                return ResourceManager.GetString("ItemTrackerTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open main plugin window{0}.
        /// </summary>
        public static string MainChatCommandHelpMessage {
            get {
                return ResourceManager.GetString("MainChatCommandHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection status locked. Inventory syncs will not uncollect.
        /// </summary>
        public static string ManuallyCollectedTooltip {
            get {
                return ResourceManager.GetString("ManuallyCollectedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNTL.
        /// </summary>
        public static string MateriaAbbrevControl {
            get {
                return ResourceManager.GetString("MateriaAbbrevControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CP.
        /// </summary>
        public static string MateriaAbbrevCraftingPoints {
            get {
                return ResourceManager.GetString("MateriaAbbrevCraftingPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRFT.
        /// </summary>
        public static string MateriaAbbrevCraftsmanship {
            get {
                return ResourceManager.GetString("MateriaAbbrevCraftsmanship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRT.
        /// </summary>
        public static string MateriaAbbrevCriticalHit {
            get {
                return ResourceManager.GetString("MateriaAbbrevCriticalHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DET.
        /// </summary>
        public static string MateriaAbbrevDetermination {
            get {
                return ResourceManager.GetString("MateriaAbbrevDetermination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DHT.
        /// </summary>
        public static string MateriaAbbrevDirectHitRate {
            get {
                return ResourceManager.GetString("MateriaAbbrevDirectHitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GATH.
        /// </summary>
        public static string MateriaAbbrevGathering {
            get {
                return ResourceManager.GetString("MateriaAbbrevGathering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GP.
        /// </summary>
        public static string MateriaAbbrevGatheringPoints {
            get {
                return ResourceManager.GetString("MateriaAbbrevGatheringPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERC.
        /// </summary>
        public static string MateriaAbbrevPerception {
            get {
                return ResourceManager.GetString("MateriaAbbrevPerception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIE.
        /// </summary>
        public static string MateriaAbbrevPiety {
            get {
                return ResourceManager.GetString("MateriaAbbrevPiety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKS.
        /// </summary>
        public static string MateriaAbbrevSkillSpeed {
            get {
                return ResourceManager.GetString("MateriaAbbrevSkillSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPS.
        /// </summary>
        public static string MateriaAbbrevSpellSpeed {
            get {
                return ResourceManager.GetString("MateriaAbbrevSpellSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TNC.
        /// </summary>
        public static string MateriaAbbrevTenacity {
            get {
                return ResourceManager.GetString("MateriaAbbrevTenacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string MateriaCountsGearsetsComboAllOption {
            get {
                return ResourceManager.GetString("MateriaCountsGearsetsComboAllOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Gearsets Selected.
        /// </summary>
        public static string MateriaCountsGearsetsComboAllSelectedPreview {
            get {
                return ResourceManager.GetString("MateriaCountsGearsetsComboAllSelectedPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Gearsets Selected.
        /// </summary>
        public static string MateriaCountsGearsetsComboCountSelectedPreview {
            get {
                return ResourceManager.GetString("MateriaCountsGearsetsComboCountSelectedPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Gearsets Loaded.
        /// </summary>
        public static string MateriaCountsGearsetsComboNoneLoadedPreview {
            get {
                return ResourceManager.GetString("MateriaCountsGearsetsComboNoneLoadedPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect All.
        /// </summary>
        public static string MateriaCountsGearsetsComboNoneOption {
            get {
                return ResourceManager.GetString("MateriaCountsGearsetsComboNoneOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Gearsets Selected.
        /// </summary>
        public static string MateriaCountsGearsetsComboNoneSelectedPreview {
            get {
                return ResourceManager.GetString("MateriaCountsGearsetsComboNoneSelectedPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which gearset(s) to check for unfilled materia.
        /// </summary>
        public static string MateriaCountsGearsetsComboTooltip {
            get {
                return ResourceManager.GetString("MateriaCountsGearsetsComboTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tab helps with getting enough materia before advanced melding for your gearsets.
        ///
        ///{0} uses the melding success rate for each unmelded slot in selected gearsets
        ///to calculate how many materia are needed to successfully fill every slot.
        ///
        ///Usage Instructions
        ///1. Select the gearsets with gearpieces you want to meld
        ///2. Set your desired meld confidence percent (currently {1}). A higher value
        ///means more materia will be needed, but there will be a lower chance (currently {2})
        ///that melding will fail and m [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MateriaCountsHelpPopupText {
            get {
                return ResourceManager.GetString("MateriaCountsHelpPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string MateriaCountsInventoryHeader {
            get {
                return ResourceManager.GetString("MateriaCountsInventoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materia Name.
        /// </summary>
        public static string MateriaCountsMateriaNameHeader {
            get {
                return ResourceManager.GetString("MateriaCountsMateriaNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meld Confidence.
        /// </summary>
        public static string MateriaCountsMeldConfidenceSliderLabel {
            get {
                return ResourceManager.GetString("MateriaCountsMeldConfidenceSliderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} chance that all selected slots are melded successfully using the amount of materia listed
        ///Inversely, {1} chance more materia than listed will be needed to meld all selected slots
        ///CTRL+Click to insert number.
        /// </summary>
        public static string MateriaCountsMeldConfidenceTooltip {
            get {
                return ResourceManager.GetString("MateriaCountsMeldConfidenceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needed.
        /// </summary>
        public static string MateriaCountsNeededHeader {
            get {
                return ResourceManager.GetString("MateriaCountsNeededHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Gearset(s) to view unmelded Materia.
        /// </summary>
        public static string MateriaCountsNoSelectedGearsets {
            get {
                return ResourceManager.GetString("MateriaCountsNoSelectedGearsets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Materia Melded for Selected Gearsets(s).
        /// </summary>
        public static string MateriaCountsNoUnmeldedMateria {
            get {
                return ResourceManager.GetString("MateriaCountsNoUnmeldedMateria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning:  Multiple gearsets using the same gearpiece may overcount materia required.
        /// </summary>
        public static string MateriaCountsOvercountWarningText {
            get {
                return ResourceManager.GetString("MateriaCountsOvercountWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the same gearpiece is used in more than one gearset, this list counts its materia twice, even if a single gearpiece in game could be shared by both
        ///If buying materia in bulk, only buy enough for one of the sets sharing a gearpiece
        ///
        ///Sets sharing gearpieces:
        ///{0}.
        /// </summary>
        public static string MateriaCountsOvercountWarningTooltip {
            get {
                return ResourceManager.GetString("MateriaCountsOvercountWarningTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining.
        /// </summary>
        public static string MateriaCountsRemainingHeader {
            get {
                return ResourceManager.GetString("MateriaCountsRemainingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in inventories for {0}.
        /// </summary>
        public static string MateriaCountsSearchInventory {
            get {
                return ResourceManager.GetString("MateriaCountsSearchInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slots.
        /// </summary>
        public static string MateriaCountsSlotsHeader {
            get {
                return ResourceManager.GetString("MateriaCountsSlotsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stat.
        /// </summary>
        public static string MateriaCountsStatHeader {
            get {
                return ResourceManager.GetString("MateriaCountsStatHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materia.
        /// </summary>
        public static string MateriaCountsTabName {
            get {
                return ResourceManager.GetString("MateriaCountsTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        public static string MateriaMeldTooltip {
            get {
                return ResourceManager.GetString("MateriaMeldTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meld.
        /// </summary>
        public static string MeldVerb {
            get {
                return ResourceManager.GetString("MeldVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Materia Melds.
        /// </summary>
        public static string MeldWindowHeader {
            get {
                return ResourceManager.GetString("MeldWindowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Gearset.
        /// </summary>
        public static string NewGearsetButton {
            get {
                return ResourceManager.GetString("NewGearsetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import a new gearset.
        /// </summary>
        public static string NewGearsetTooltip {
            get {
                return ResourceManager.GetString("NewGearsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum of {0} gearsets.
        /// </summary>
        public static string NewGearsetTooltipMaxGearsets {
            get {
                return ResourceManager.GetString("NewGearsetTooltipMaxGearsets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No gearsets found. Add one or more gearsets to get started.
        /// </summary>
        public static string NoGearsetsText {
            get {
                return ResourceManager.GetString("NoGearsetsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item not collected.
        /// </summary>
        public static string NotObtainableHelp {
            get {
                return ResourceManager.GetString("NotObtainableHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some prerequisite(s) collected.
        /// </summary>
        public static string NotObtainablePartialHelp {
            get {
                return ResourceManager.GetString("NotObtainablePartialHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item obtainable using prerequisites.
        /// </summary>
        public static string ObtainableHelp {
            get {
                return ResourceManager.GetString("ObtainableHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item collected.
        /// </summary>
        public static string ObtainedCompleteHelp {
            get {
                return ResourceManager.GetString("ObtainedCompleteHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item collected, missing materia.
        /// </summary>
        public static string ObtainedPartialHelp {
            get {
                return ResourceManager.GetString("ObtainedPartialHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open config.
        /// </summary>
        public static string OpenConfigTooltip {
            get {
                return ResourceManager.GetString("OpenConfigTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popout Configuration.
        /// </summary>
        public static string OpenExternalConfigWindowTooltip {
            get {
                return ResourceManager.GetString("OpenExternalConfigWindowTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BISBuddy.
        /// </summary>
        public static string PluginDisplayName {
            get {
                return ResourceManager.GetString("PluginDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prerequisites.
        /// </summary>
        public static string PrerequisiteGearpieceHeader {
            get {
                return ResourceManager.GetString("PrerequisiteGearpieceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles.
        /// </summary>
        public static string PrerequisiteOrNodeSettingsTabName {
            get {
                return ResourceManager.GetString("PrerequisiteOrNodeSettingsTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to include or ignore this method of obtaining the parent item.
        /// </summary>
        public static string PrerequisiteOrNodeToggleTooltip {
            get {
                return ResourceManager.GetString("PrerequisiteOrNodeToggleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left click to {0}
        ///Right click to search for in inventory.
        /// </summary>
        public static string PrerequisiteTooltipBase {
            get {
                return ResourceManager.GetString("PrerequisiteTooltipBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Gearset.
        /// </summary>
        public static string RenameGearsetTooltip {
            get {
                return ResourceManager.GetString("RenameGearsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Colors &amp; Styles.
        /// </summary>
        public static string ResetUiThemeButton {
            get {
                return ResourceManager.GetString("ResetUiThemeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset plugin styles/colors to default.
        /// </summary>
        public static string ResetUiThemeTooltip {
            get {
                return ResourceManager.GetString("ResetUiThemeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search inventory for {0}.
        /// </summary>
        public static string SearchInventoryForItemTooltip {
            get {
                return ResourceManager.GetString("SearchInventoryForItemTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Gearset Color Accent.
        /// </summary>
        public static string ShowGearsetColorAccentFlagLabel {
            get {
                return ResourceManager.GetString("ShowGearsetColorAccentFlagLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to display a gradient of the gearset highlight color on the gearset tab and header.
        /// </summary>
        public static string ShowGearsetColorAccentFlagTooltip {
            get {
                return ResourceManager.GetString("ShowGearsetColorAccentFlagTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strict Materia Matching.
        /// </summary>
        public static string StrictMateriaMatchingCheckbox {
            get {
                return ResourceManager.GetString("StrictMateriaMatchingCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether auto assignment treats gearpieces with different materia as unique items
        ///
        ///When ON: Each gearpiece entry is considered unique based on its materia. So if you have multiple entries for the same gearpiece with different materia, a single inventory item can only satisfy one of them
        ///When OFF: Auto assignment ignores the materia differences and only looks at the actual gearpiece. One inventory item can satisfy multiple entries for the same gearpiece even if their materia differ
        ///
        ///Example
        ///Inventory: 1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string StrictMateriaMatchingHelp {
            get {
                return ResourceManager.GetString("StrictMateriaMatchingHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Inventory.
        /// </summary>
        public static string SyncInventoryButton {
            get {
                return ResourceManager.GetString("SyncInventoryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update gearsets with items from your inventory.
        /// </summary>
        public static string SyncInventoryTooltip {
            get {
                return ResourceManager.GetString("SyncInventoryTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gearpiece Buttons.
        /// </summary>
        public static string UiThemeColorGearpieceButton {
            get {
                return ResourceManager.GetString("UiThemeColorGearpieceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gearpiece Buttons (Clicked).
        /// </summary>
        public static string UiThemeColorGearpieceButtonActive {
            get {
                return ResourceManager.GetString("UiThemeColorGearpieceButtonActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gearpiece Buttons (Hovered).
        /// </summary>
        public static string UiThemeColorGearpieceButtonHovered {
            get {
                return ResourceManager.GetString("UiThemeColorGearpieceButtonHovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materia Slot (Advanced).
        /// </summary>
        public static string UiThemeColorMateriaSlotAdvancedLabel {
            get {
                return ResourceManager.GetString("UiThemeColorMateriaSlotAdvancedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materia Slot (Normal).
        /// </summary>
        public static string UiThemeColorMateriaSlotNormalLabel {
            get {
                return ResourceManager.GetString("UiThemeColorMateriaSlotNormalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gearset Colors.
        /// </summary>
        public static string UiThemeConfigColorsSectionHeader {
            get {
                return ResourceManager.GetString("UiThemeConfigColorsSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaults.
        /// </summary>
        public static string UiThemeConfigResetsSectionHeader {
            get {
                return ResourceManager.GetString("UiThemeConfigResetsSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gearset Styles.
        /// </summary>
        public static string UiThemeConfigStylesSectionHeader {
            get {
                return ResourceManager.GetString("UiThemeConfigStylesSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock as Collected.
        /// </summary>
        public static string UncollectedTooltip {
            get {
                return ResourceManager.GetString("UncollectedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncollect.
        /// </summary>
        public static string UncollectVerb {
            get {
                return ResourceManager.GetString("UncollectVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ???.
        /// </summary>
        public static string UnknownClassJobAbbreviation {
            get {
                return ResourceManager.GetString("UnknownClassJobAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Class/Job.
        /// </summary>
        public static string UnknownClassJobName {
            get {
                return ResourceManager.GetString("UnknownClassJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmeld.
        /// </summary>
        public static string UnmeldVerb {
            get {
                return ResourceManager.GetString("UnmeldVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Changes.
        /// </summary>
        public static string UpdateOnItemChangeCheckbox {
            get {
                return ResourceManager.GetString("UpdateOnItemChangeCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a change is detected in character inventories, update gearsets with items in inventories (inventory, armoury chest, equipped).
        /// </summary>
        public static string UpdateOnItemChangeHelp {
            get {
                return ResourceManager.GetString("UpdateOnItemChangeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login/Load.
        /// </summary>
        public static string UpdateOnLoginLoadCheckbox {
            get {
                return ResourceManager.GetString("UpdateOnLoginLoadCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When logging in or loading {0}, update gearsets with items in inventories (inventory, armoury chest, equipped).
        /// </summary>
        public static string UpdateOnLoginLoadHelp {
            get {
                return ResourceManager.GetString("UpdateOnLoginLoadHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Changes.
        /// </summary>
        public static string UpdateOnPluginChangesCheckbox {
            get {
                return ResourceManager.GetString("UpdateOnPluginChangesCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When updating {0} gearsets or settings, update gearsets with items in inventories (inventory, armoury chest, equipped).
        /// </summary>
        public static string UpdateOnPluginChangesHelp {
            get {
                return ResourceManager.GetString("UpdateOnPluginChangesHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gearsets.
        /// </summary>
        public static string UserGearsetsTabName {
            get {
                return ResourceManager.GetString("UserGearsetsTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a gearset.
        /// </summary>
        public static string UserGearsetsTabNoGearsetsTextNavigation {
            get {
                return ResourceManager.GetString("UserGearsetsTabNoGearsetsTextNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gearset details appear here.
        /// </summary>
        public static string UserGearsetsTabNoGearsetsTextPanel {
            get {
                return ResourceManager.GetString("UserGearsetsTabNoGearsetsTextPanel", resourceCulture);
            }
        }
    }
}
